# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 02:48
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('beer_name', models.CharField(max_length=100)),
                ('beer_avg_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('beer_abv', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('beer_srm', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('beer_logo', models.URLField(max_length=100)),
                ('beer_photo', models.FileField(blank=True, upload_to=b'')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name=b'slug')),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('brewery_name', models.CharField(max_length=100)),
                ('brewery_location', models.CharField(max_length=250)),
                ('brewery_founding', models.PositiveSmallIntegerField()),
                ('brewery_logo', models.URLField(max_length=100)),
                ('brewery_photo', models.FileField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_score', models.CharField(choices=[(b'1', b'*'), (b'2', b'**'), (b'3', b'***'), (b'4', b'****'), (b'5', b'*****')], max_length=5, null=True)),
                ('rating_beer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beers.Beer')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=100)),
                ('style_group', models.CharField(choices=[(b'ALE', b'Ale'), (b'LGR', b'Lager')], max_length=3)),
                ('style_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beers.Brewery'),
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beers.Style'),
        ),
    ]
