# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=100)),
                ('beer_style', models.CharField(choices=[(b'ASA', b'American Strong Ale'), (b'AMW', b'American Wheat'), (b'BAW', b'Barleywine'), (b'BNA', b'Brown Ale'), (b'CAC', b'California Common'), (b'ESB', b'Extra Special Bitter'), (b'HEF', b'Hefeweizen'), (b'IPA', b'India Pale Ale'), (b'OKT', b'Oktoberfest'), (b'PAL', b'Pale Ale'), (b'PIL', b'Pilsner'), (b'PTR', b'Porter'), (b'QUD', b'Quadrupel'), (b'STT', b'Stout'), (b'VNL', b'Vienna Lager')], max_length=3)),
                ('beer_logo', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_name', models.CharField(max_length=100)),
                ('brewery_location', models.CharField(max_length=250)),
                ('brewery_founding', models.IntegerField()),
                ('brewery_logo', models.URLField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.Brewery'),
        ),
    ]
