# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
