# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20180111_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='slug',
            new_name='beer_slug',
        ),
        migrations.AddField(
            model_name='brewery',
            name='brewery_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
