# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20170725_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_score',
            field=models.CharField(choices=[(b'1', b'*'), (b'2', b'**'), (b'3', b'***'), (b'4', b'****'), (b'5', b'*****')], max_length=5, null=True),
        ),
    ]
