# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_beer_beer_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='brewery_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
