# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_rating_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_abv',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_srm',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='brewery_founding',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
