# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20180111_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='brewery_slug',
        ),
    ]
