# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_auto_20170726_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='beer_add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='brewery_add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
