# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_remove_brewery_brewery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='beer_slug',
        ),
    ]
