# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20171019_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='brewery_add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
